# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orchestrator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'orchestrator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12orchestrator.proto\x12\x0corchestrator\"-\n\x08LineItem\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"o\n\x0f\x43heckoutRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12%\n\x05items\x18\x03 \x03(\x0b\x32\x16.orchestrator.LineItem\x12\x12\n\ntotal_cost\x18\x04 \x01(\x05\":\n\x10\x43heckoutResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t2e\n\x13OrchestratorService\x12N\n\rStartCheckout\x12\x1d.orchestrator.CheckoutRequest\x1a\x1e.orchestrator.CheckoutResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orchestrator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LINEITEM']._serialized_start=36
  _globals['_LINEITEM']._serialized_end=81
  _globals['_CHECKOUTREQUEST']._serialized_start=83
  _globals['_CHECKOUTREQUEST']._serialized_end=194
  _globals['_CHECKOUTRESPONSE']._serialized_start=196
  _globals['_CHECKOUTRESPONSE']._serialized_end=254
  _globals['_ORCHESTRATORSERVICE']._serialized_start=256
  _globals['_ORCHESTRATORSERVICE']._serialized_end=357
# @@protoc_insertion_point(module_scope)
