apiVersion: v1
kind: Service
metadata:
  name: orchestrator-service
spec:
  type: ClusterIP
  selector:
    component: orchestrator
  ports:
    - port: 5000
      name: http
      targetPort: 5000
    - port: 50053
      name: grpc
      targetPort: 50053
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: orchestrator
  template:
    metadata:
      labels:
        component: orchestrator
    spec:
      containers:
        - name: orchestrator
          image: orchestrator:latest
          command: ["uvicorn"]
          args: ["app:app", "--host", "0.0.0.0", "--port", "5000", "--workers", "1"]
          ports:
            - containerPort: 5000
            - containerPort: 50053
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          env:
            - name: REDIS_NODE_HOST
              value: "payment-redis-cluster-redis-cluster"
            - name: REDIS_PASSWORD
              value: "redis"
            - name: STOCK_GRPC_ADDR
              value: "stock-service:50051"
            - name: PAYMENT_GRPC_ADDR
              value: "payment-service:50051"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
