cluster:
  nodes: 6
  replicas: 1

usePassword: true
password: "redis"

commonConfiguration: |-
  appendonly yes
  appendfsync everysec
  maxmemory-policy noeviction

redis:
  useAOFPersistence: "yes"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi

persistence:
  enabled: true
  size: 1Gi

podManagementPolicy: Parallel
